Make fn var argument mutable typo fix
jzarnett/ece459 pull request #63
Opened 2021-02-26 05:02 UTC by NathanielRN

As mentioned in [Lecture 18 @ 12:50](https://youtu.be/iHVUVyVZBK0?t=770) the y value (and I'm assuming the z value?) need to be mutable `mut` in the function signature.

2021-03-07 03:27 UTC, bkthomps approved these changes
lgtm

2021-03-07 03:27 UTC, bkthomps commented
@jzarnett merge?

2021-03-07 14:23 UTC, jzarnett commented
So I looked at this but the original version without the `mut` added to x and y still compiles. The new declarations of `let x =...` and `let y = ...` are an example of shadowing. So they don't _have_ to be mutable for the example to compile and run.

Now, I didn't watch the video segment again before writing this, so maybe there's something else in the video referencing the variables that means it makes sense for them to be `mut`?

2021-03-09 14:16 UTC, jzarnett requested changes
I need a bit more explanation as to why this is needed? 🤔

2021-03-10 23:16 UTC, bkthomps commented
@NathanielRN

2021-03-10 23:19 UTC, NathanielRN commented
I'll close this since you said it works! Although I would say that's it's confusing to use the same value as the function argument variable even if it works with shadowing...

2021-03-10 23:19 UTC, closed without merging

2021-03-12 02:17 UTC, bkthomps commented
I would say shadowing is fine, but putting three variable declarations on the same line isn't great.